name: Windows Cuda Build
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Whisper.cpp tag, branch or commit to build'
        default: v1.8.2

  workflow_call:

jobs:
  build-windows-cuda:
    name: Build for Windows (x86_64, CUDA)
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout whisper.cpp
        uses: actions/checkout@v4
        with:
          repository: ggerganov/whisper.cpp
          ref: ${{ github.event.inputs.version }}
          path: whisper.cpp

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Install CUDA Toolkit
        id: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: '12.2.0'

      - name: Run build script
        run: |
          cd whisper.cpp
          cmake -S . -B ./build -A x64 -DCMAKE_BUILD_TYPE=Release -DWHISPER_CUBLAS=ON -DWHISPER_BUILD_TESTS=OFF -DWHISPER_BUILD_EXAMPLES=OFF
          cd ./build
          msbuild ALL_BUILD.vcxproj -t:build -p:configuration=Release -p:platform=x64
          cd ${{ github.workspace }}\whisper.cpp\build\bin\Release
          ren whisper.dll libwhisper_cuda.dll

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: whisper.cpp/build/bin/Release/libwhisper_cuda.dll
